title: jekyll - octopod
url: https://jekyll-octopod.github.io
subtitle: Static Site Podcast Publishing for Geeks
description: Static Site Podcast Publishing for Geeks.
author: Stefan Haslinger
email: stefan.haslinger@informatom.com
keywords: [octopod, podcast, magic]
itunes_categories: [Technology]
episodes_per_feed_page: 100

poster: /img/logo-360x360.png
alwaysShowHours: true
startVolume: 0.8
width: auto
summaryVisible: false
timecontrolsVisible: false
chaptersVisible: true
sharebuttonsVisible: false

twitter_nick: jekyll_octopod
language: en
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY 4.0

itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
theme: jekyll-bootflat

